/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentarAutos;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 *
 * @author Usuario
 */
public class frmMenu extends javax.swing.JFrame {

    //Agregar un objeto de la clase carros
    //nuevo atributo para el formulario menu
    Carros miscarros = new Carros();
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        //Agregar al constructor del formulario menu
 
 
 
    //abrir el archivo
        //leer linea por linea
        //diferenciar dato por datos con punto y coma
        //llenar los arreglos
        StringBuilder sb = new StringBuilder();
                                                                   //en donde yo lo tenga                    
        try (BufferedReader br = Files.newBufferedReader(Paths.get("C:\\Users\\Usuario\\Desktop\\vehiculos.csv"))) {
 
            // read line by line
            String line;
            String placas = "";
            int i, j = 0;
            while ((line = br.readLine()) != null) {
                i = 0;
 
                while (line.charAt(i) != ';') {
                    placas += line.charAt(i);
                    i++;
                }
                //System.out.println(placas);
                miscarros.placas[j] = placas;
                System.out.println(miscarros.placas[j]);
                placas = "";
                j++;
            }
 
        } catch (IOException e) {
            System.err.format("IOException: %s%n", e);
            System.out.println("Error en la lectura del archivo");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRentar = new javax.swing.JMenu();
        mnuDisponible = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        frnModificar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuRentar.setText("Rentar autos");
        mnuRentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRentarActionPerformed(evt);
            }
        });

        mnuDisponible.setText("Ver disponibles");
        mnuDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDisponibleActionPerformed(evt);
            }
        });
        mnuRentar.add(mnuDisponible);

        jMenuBar1.add(mnuRentar);

        jMenu2.setText("Devolver vehiculos");

        jMenuItem6.setText("ver vehiculos por devolver");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Gestionar vehiculos");

        jMenuItem1.setText("Agregar");
        jMenu5.add(jMenuItem1);

        frnModificar.setText("modificar");
        frnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frnModificarActionPerformed(evt);
            }
        });
        jMenu5.add(frnModificar);

        jMenuItem3.setText("eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator1);

        jMenu6.setText("ventana");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Datos cliente");

        jMenuItem7.setText("agregar datos cliente");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnuRentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRentarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuRentarActionPerformed

    private void mnuDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDisponibleActionPerformed
        // TODO add your handling code here:
        Renta rentar = new Renta(this,true,miscarros,1);
        rentar.setVisible(true);
    }//GEN-LAST:event_mnuDisponibleActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Renta rentar = new Renta(this,true,miscarros,2);
        rentar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void frnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frnModificarActionPerformed
        // TODO add your handling code here:
        frmModificar editar = new frmModificar(this, true, miscarros);
        editar.setVisible(true);
    }//GEN-LAST:event_frnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frnModificar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuDisponible;
    private javax.swing.JMenu mnuRentar;
    // End of variables declaration//GEN-END:variables
}

